"""
fix_stale_live_pages.py
ONE-OFF MAINTENANCE SCRIPT.

Problem:
  Streams whose stream_status was stuck 'live' in the database were generated
  as LIVE pages. The database has since been corrected (stream_status = 'vod'
  via SQL cleanup), and the manifest may now say 'vod' for these streams too
  (from a run that correctly read 'vod' from the DB after the cleanup).
  But the page file on disk still contains the stale LIVE badge and content
  from when it was first generated. Since compute_dirty_set sees
  was_live=False and is_live_now=False, it considers these streams permanently
  clean and never regenerates them.

What this script does:
  Scans every stream page in dashboard/ and checks whether the HTML file
  contains the LIVE badge marker. If it does, and the manifest says 'vod'
  (meaning the DB confirmed it's finished), the manifest entry is cleared
  so that generate_backfill.py will treat it as a new/unseen stream and
  regenerate the page with the correct VOD content on the next run.

What this script does NOT do:
  - It does not regenerate pages itself (that's generate_backfill.py's job).
  - It does not touch streams correctly marked as live in the manifest.
  - It does not modify the database.

Run once, then trigger generate_backfill.py (workflow_dispatch on
deploy_dashboard_backfill.yml) to regenerate the cleared pages.
Delete this script after confirming the dashboard looks correct.
"""

import json
import re
from pathlib import Path
import os

OUTPUT_DIR   = Path(os.environ.get("DASHBOARD_OUTPUT_DIR", "dashboard"))
MANIFEST_PATH = OUTPUT_DIR / "manifest.json"

# Marker string present in every generated LIVE stream page.
# Matches the status badge rendered by write_stream_page for live streams.
LIVE_MARKER = "status-live"


def main():
    if not MANIFEST_PATH.exists():
        print(f"ERROR: manifest not found at {MANIFEST_PATH}")
        raise SystemExit(1)

    with open(MANIFEST_PATH, encoding="utf-8") as f:
        manifest = json.load(f)

    print(f"Manifest loaded — {len(manifest)} entries.")

    cleared = 0
    skipped_genuinely_live = 0
    skipped_no_file = 0
    skipped_already_correct = 0

    for vid, entry in list(manifest.items()):
        status = entry.get("status", "vod")

        # Don't touch genuinely live streams — their pages SHOULD show LIVE.
        if status == "live":
            skipped_genuinely_live += 1
            continue

        # Reconstruct the page file path from the manifest entry.
        org_slug = entry.get("org_slug", "")
        ch_slug  = entry.get("ch_slug", "")
        # slugify video_id — lowercase, replace non-alphanumeric with hyphens
        v_slug   = re.sub(r"[^a-z0-9]+", "-", vid.lower()).strip("-")
        page_path = OUTPUT_DIR / org_slug / ch_slug / f"{v_slug}.html"

        if not page_path.exists():
            # File doesn't exist — file_missing check in compute_dirty_set
            # handles this case already (or will once that fix is deployed).
            skipped_no_file += 1
            continue

        # Read the file and check for the LIVE badge marker.
        try:
            content = page_path.read_text(encoding="utf-8", errors="ignore")
        except Exception as e:
            print(f"  WARNING: could not read {page_path}: {e}")
            continue

        if LIVE_MARKER not in content:
            # Page already shows VOD content — nothing to fix.
            skipped_already_correct += 1
            continue

        # Page file exists, manifest says 'vod', but page has LIVE content.
        # Clear the manifest entry so generate_backfill.py treats it as new
        # and regenerates the page with the correct VOD content.
        del manifest[vid]
        cleared += 1
        print(f"  Cleared manifest entry for {vid} ({org_slug}/{ch_slug}) — stale LIVE page detected.")

    print(f"\nDone.")
    print(f"  Cleared:                 {cleared} stale LIVE page(s) — will be regenerated by backfill.")
    print(f"  Skipped (genuinely live): {skipped_genuinely_live}")
    print(f"  Skipped (no file):        {skipped_no_file}")
    print(f"  Skipped (already correct): {skipped_already_correct}")

    if cleared == 0:
        print("\nNothing to fix — all VOD pages have correct content.")
        return

    # Write updated manifest back.
    tmp = MANIFEST_PATH.with_suffix(".tmp")
    tmp.write_text(json.dumps(manifest, ensure_ascii=False, indent=None), encoding="utf-8")
    tmp.replace(MANIFEST_PATH)
    print(f"\nManifest updated — {len(manifest)} entries remaining.")
    print("Next step: trigger generate_backfill.py (workflow_dispatch on deploy_dashboard_backfill.yml)")
    print("to regenerate the cleared pages with correct VOD content.")


if __name__ == "__main__":
    main()
