"""
force_regen_stream_pages.py
ONE-OFF MAINTENANCE SCRIPT — not part of the regular live/backfill pipeline.

Why this exists:
compute_dirty_set() treats a stream as "permanently clean" once it has a
manifest entry with status "vod" AND its .html file exists on disk. That
rule has no concept of "the shared HTML template changed" — it only tracks
per-video_id live/ended/missing state. So when _html_head() gains a new
sitewide element (e.g. the Google Analytics snippet added for GA4 rollout),
every stream page that already existed at deploy time keeps serving its old
<head> forever. Only brand-new streams generated after the change go
through the current write_stream_page() -> _html_head() path and pick it up
automatically.

force_regen_pages.py (the existing script) already solves this same problem
for channel and org pages, but explicitly skips stream pages — at the time
it was written, stream data itself hadn't changed, so re-rendering ~3800
video pages was pure wasted cost for that particular bug. A sitewide <head>
change is the opposite case: the *data* didn't change, but literally every
stream page's <head> is stale until it's rewritten. This script is the
missing complement — run it alongside force_regen_pages.py for full
coverage after any change to _html_head() or the shared page chrome.

What this script does:
  - Fetches the full live+archive stream set for every resolved channel
    (same fetch_all_streams() used by generate_live.py / generate_backfill.py
    / force_regen_pages.py).
  - Treats EVERY stream's video_id as dirty, ignoring manifest.json state
    entirely, and regenerates every stream page unconditionally via the same
    generate_stream_pages() helper the live/backfill loops use (same retry
    logic, same threaded worker pool, same enrichment path).

What this script deliberately does NOT do:
  - It does not read or write manifest.json. Manifest only tracks stream
    page dirty-state; leaving it untouched means generate_live.py /
    generate_backfill.py continue exactly as before after this runs — a
    stream regenerated here with the same status ("vod") it already had in
    the manifest stays exactly as clean/dirty as it was.
  - It does not touch channel or org pages — that's force_regen_pages.py's
    job. Run both scripts for a full sitewide repaint.
  - It does not call get_channel_data() (the YouTube channels.list API used
    for logos/subscriber counts). Stream detail pages don't render either of
    those, so there is no reason to spend API quota fetching them here.
    load_channel_maps() is intentionally NOT used for this reason; this
    script fetches channel rows directly instead.
  - It does not regenerate index.html or live.html. Those are always
    regenerated by every live/backfill run regardless, so they already pick
    up _html_head() changes on the very next scheduled run.

This is safe to run multiple times — idempotent, and doesn't mutate any
shared state the regular pipeline depends on. Because it opens its own
short-lived per-worker connections (the same pattern generate_stream_pages()
already uses), it's also safe to run concurrently with the live/backfill
loops, though for a clean first run it's simplest to wait for the current
run to finish first.

Cost note: most streams being regenerated here are already-finished VODs.
Archived ones (moved into history.db by archiver.py) only need a SQLite
read per page — no Postgres connection at all. Only streams still inside
the live 30-day Postgres window pay the Postgres round-trip. Either way,
this is thousands of small, independent writes rather than thousands of
expensive queries.
"""

from dashboard_core import (
    AIVEN_DATABASE_URL, log, _now_local,
    get_conn, get_history_conn, get_channel_rows, _load_schema_cache,
    setup_output_dirs, resolve_channels,
    fetch_all_streams, build_dirty_work_list, generate_stream_pages,
    ORG_MAP,
)


def force_regen_stream_pages() -> None:
    if not AIVEN_DATABASE_URL:
        print("ERROR: DATABASE_URL / AIVEN_DATABASE_URL environment variable is not set.")
        raise SystemExit(1)

    conn = get_conn()
    hist = get_history_conn()
    if hist is None:
        log.warning(
            "history.db not found/openable — this run would only regenerate "
            "streams still inside the live 30-day Postgres window and would "
            "silently skip the (much larger) archived history. Aborting."
        )
        raise SystemExit(1)

    setup_output_dirs()

    # Deliberately bypass load_channel_maps() here — it also calls
    # get_channel_data() (YouTube channels.list) to fetch logos/subscriber
    # counts, neither of which stream detail pages render. Fetch just the
    # channel registry rows and warm the schema cache directly instead.
    db_channels = get_channel_rows(conn)
    db_by_name  = {ch["channel_name"]: ch for ch in db_channels}
    db_by_id    = {ch["channel_id"]:   ch for ch in db_channels}
    _load_schema_cache(conn, [ch["table_name"] for ch in db_channels])

    resolved_channels = resolve_channels(db_by_name, db_by_id)

    all_streams_by_channel, stream_counts, total_streams, total_channels = \
        fetch_all_streams(conn, hist, resolved_channels)

    # Force EVERY known video_id to be treated as dirty, bypassing
    # manifest-based dirty tracking entirely — this is the whole point.
    dirty_video_ids = {
        stream["video_id"]
        for streams in all_streams_by_channel.values()
        for stream in streams
    }

    log.info(
        "Force-regen: rewriting %d stream page(s) across %d channel(s) "
        "regardless of manifest/dirty-tracking state (%d total streams known "
        "across %d resolved channels).",
        len(dirty_video_ids), len(resolved_channels),
        total_streams, total_channels,
    )

    if not dirty_video_ids:
        log.info("Nothing to regenerate — no streams found for any resolved channel.")
        conn.close()
        hist.close()
        return

    dirty_work = build_dirty_work_list(resolved_channels, all_streams_by_channel, dirty_video_ids)

    run_ts = _now_local().strftime("%Y-%m-%d %H:%M WIB")
    # Conservative worker count, same reasoning as generate_backfill.py:
    # this is a large one-off backlog rather than a time-sensitive loop, so
    # a gentler concurrency level avoids any connection-burst issues with
    # Supabase/PgBouncer for the subset of streams still in the live window.
    new_entries = generate_stream_pages(dirty_work, run_ts, max_workers=6)

    conn.close()
    hist.close()

    log.info(
        "Force-regen complete — %d/%d stream page(s) rewritten. "
        "manifest.json was NOT touched; channel/org pages were NOT touched "
        "(run force_regen_pages.py separately for those).",
        len(new_entries), len(dirty_video_ids)
    )
    if len(new_entries) < len(dirty_video_ids):
        log.warning(
            "%d stream page(s) failed to regenerate (see errors above) and "
            "were skipped — safe to re-run this script to retry just those.",
            len(dirty_video_ids) - len(new_entries)
        )


if __name__ == "__main__":
    force_regen_stream_pages()
